spring:
  application:
    name: lucy-bot
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:postgresql://localhost:5432/lucy
    username: postgres
    password: masterkey
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
#        enable_lazy_load_no_trans: true
  main:
    allow-circular-references: true
  flyway:
    enabled: true
    validate-on-migrate: true
    locations:
      classpath:db/migration
    schemas: lucy

lucy:
  token: tokenaqui